django_app/_config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('accounts.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
	path('dynamo/', include('dynamo.urls')),
]

django_app/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('accounts/register/', views.RegisterView.as_view(), name='register'),
	path('accounts/login/', views.LoginView.as_view(), name='login'),
	path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
]

django_app/dynamo/urls.py
from django.urls import path
from . import views

app_name = 'dynamo'

urlpatterns = [
	path('', views.CreateModelView.as_view(), name='create_model'),
	path('list_models/', views.ListModelsView.as_view(), name='list_models'),
]

django_app/accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
	pass

django_app/dynamo/models.py
from django.db import models

# Create your models here.

django_app/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class CustomUserCreationForm(UserCreationForm):
	def __init__(self, *args, **kwargs):
		super(CustomUserCreationForm, self).__init__(*args, **kwargs)
		self.fields.pop('password2')

	shared = forms.BooleanField(required=False)
	class Meta:
		model = get_user_model()
		fields = ["username", "password1", "shared"]


class CustomUserLoginForm(AuthenticationForm):
	shared = forms.BooleanField(required=False)
	class Meta:
		model = get_user_model()
		fields = ["username", "password", "shared"]

django_app/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from .forms import CustomUserCreationForm, CustomUserLoginForm
import redis
from os import getenv

redis_host = getenv("redis_host", default="localhost")
redis_db = redis.StrictRedis(host=redis_host, port=6379)

User = get_user_model()


def set_redis(session_key, username, is_shared):
	redis_db.set(session_key, username)
	redis_db.set(f"{session_key}_shared", [0, 1][is_shared])


def logout_current_user(request):
	try:
		session_key = request.session.session_key
		redis_db.delete(*[session_key, f"{session_key}_shared"])
	except redis.exceptions.DataError:
		pass
	if request.user.is_authenticated:
		logout(request)


class RegisterView(View):
	def get(self, request):
		form = CustomUserCreationForm()
		return render(request, "registration/register.html", context={"form": form})

	def post(self, request):
		form = CustomUserCreationForm(request.POST)
		if form.is_valid():
			logout_current_user(request)
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password1')
			is_shared = form.cleaned_data.get('shared')
			exists = User.objects.filter(username=username).first()
			if not exists:
				new_user = User(username=username)
				new_user.set_password(password)
				new_user.is_staff = True
				new_user.is_superuser = True
				new_user.save()
				user = authenticate(username=username, password=password)
				login(request, user)
				set_redis(request.session.session_key, username, is_shared)
				messages.success(request, "Successfully created new account.")
				return redirect("accounts:home")
			else:
				messages.error(request, "User with that username already exists.")
		else:
			messages.error(request, "Invalid input, try again.")

		form = CustomUserCreationForm()
		return render(request, "registration/register.html", context={"form": form})


class LoginView(View):
	def get(self, request):
		form = CustomUserLoginForm()
		return render(request, "registration/login.html", context={"form": form})

	def post(self, request):
		form = CustomUserLoginForm(request, data=request.POST)
		if form.is_valid():
			logout_current_user(request)
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			is_shared = form.cleaned_data.get('shared')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				set_redis(request.session.session_key, username, is_shared)
				redirect_url = request.GET.get("next")
				if not redirect_url:
					return redirect(reverse_lazy("accounts:home"))
				return redirect(redirect_url)
			else:
				messages.error(request, "Invalid username or password")
		else:
			messages.error(request, "Invalid username or password")
		form = CustomUserLoginForm()
		return render(request, "registration/login.html", context={"form": form})


class HomeView(View):
	def get(self, request):
		session_key = request.COOKIES.get('sessionid')
		try:
			is_shared = int(redis_db.get(f"{session_key}_shared").decode('utf-8'))
		except (redis.exceptions.DataError, AttributeError):
			is_shared = None
		return render(request, 'home.html', context={"is_shared": is_shared})


class LogoutView(View):
	def get(self, request):
		logout_current_user(request)
		redirect_url = request.GET.get('next')
		if redirect_url:
			return redirect(redirect_url)
		return redirect("/")

django_app/dynamo/views.py
from importlib import reload, import_module
from django.contrib import messages, admin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.apps import apps
from django.urls import clear_url_caches
from django.conf import settings
from django.db.utils import IntegrityError
from dynamic_models.models import ModelSchema, FieldSchema


class CreateModelView(View):
	def get(self, request):
		return render(request, "dynamo/create_model.html")

	def post(self, request):
		model_name = request.POST.get("model_name")
		if not model_name:
			messages.error(request, "Please provide model name")
		try:
			new_schema = ModelSchema.objects.create(name=model_name)

			fields = (len(request.POST) - 2) // 2
			added_fields = []
			for i in range(1, fields + 1):
				field_name = request.POST.get(f"name_field_{i}")
				if field_name and field_name not in added_fields:
					FieldSchema.objects.create(
						name=field_name,
						data_type=request.POST.get(f"type_field_{i}"),
						model_schema=new_schema,
					)

			NewModel = new_schema.as_model()

			admin.site.register(NewModel)
			reload(import_module(settings.ROOT_URLCONF))
			clear_url_caches()

			messages.success(request,
							 f"Model {NewModel.__name__} sucessfully created. You can navigate to 'Dynamo/List Models'")
		except IntegrityError:
			messages.error(request, "Model with such name already exists!")
		return redirect(reverse_lazy("dynamo:create_model"))


class ListModelsView(View):
	def get(self, request):
		all_models = apps.get_models()
		dyno_models = [model.__name__ for model in all_models if model._meta.app_label == 'dynamo']
		return render(request, "dynamo/list_models.html", context={"dyno_models": dyno_models})

django_app/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
          crossorigin="anonymous"></script>
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>

{% block navigation %}
{% include '_navigation.html' %}
{% endblock navigation %}

<section class="my-5">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-9 col-lg-8 col-xl-8">
        <div class="card shadow-lg" style="border-radius: 1.5rem">
          <div class="card-body p-5 text-center">
            {% block body %}
            {% endblock body %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% block msg %}
{% include 'messages.html' %}
{% endblock msg %}

</body>
</html>

django_app/templates/_navigation.html
<nav class="navbar navbar-expand-md bg-light shadow">
  <div class="container-fluid w-75">
    <a class="navbar-brand" href="{% url 'accounts:home' %}">This is Django App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav mx-auto">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dynamo
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="nav-link" href="{% url 'dynamo:create_model' %}">Create Model</a></li>
            <li><a class="nav-link" href="{% url 'dynamo:list_models' %}">List Models</a></li>
          </ul>
<!--        <a class="nav-link" href="/admin">Admin</a>-->
        {% else %}
        <a class="nav-link me-5" href="{% url 'accounts:login' %}">Log in</a>
        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        {% endif %}
      </div>
      <a class="navbar-brand" href="http://127.0.0.1:5000">Go to Flask App</a>
    </div>
  </div>
</nav>

django_app/templates/dynamo/create_model.html
{% extends "_base.html" %}
{% load static %}

{% block title %}
Create Model
{% endblock title %}

{% block body %}
<h2>Create Dynamic Model</h2>
<form method="post" novalidate>
  {% csrf_token %}
  <div class="input-group my-3">
    <input type="text" name="model_name" placeholder="model name..." required class="form-control form-control-lg">
    <button id="add_field" type="button" class="btn btn-primary">Add field</button>
  </div>
  <div id="form-list">
  
  </div>
  
  <button type="submit" class="btn btn-success my-2">Submit</button>
</form>


<script src="{% static 'dynamo/js/dynamo.js' %}"></script>
{% endblock body %}

django_app/templates/dynamo/list_models.html
{% extends '_base.html' %}

{% block title %}
List Models
{% endblock title %}

{% block body %}


{% if dyno_models %}
<h3 class="mt-5">These are dynamically created models:</h3>
{% for model in dyno_models %}
<a href="/admin/dynamo/{{model|lower}}"><h4 class="my-3">{{model}}</h4></a>
{% endfor %}
{% else %}
<h3>No models to show here yet...</h3>
{% endif %}

{% endblock body %}

django_app/templates/home.html
{% extends '_base.html' %}

{% block title %}
Home
{% endblock title %}

{% block body %}

{% if user.is_authenticated %}
<h3 class="mb-3">Welcome <strong>{{user.username|upper}}</strong>!</h3>
<h3 class="mb-5">Your session is already here.</h3>
<h4>
  You've chosen
  <strong> {% if not is_shared %} NOT {% endif %} TO SHARE </strong>
  this session with Flask.
</h4>
<h4>
  <a class="btn btn-outline-secondary me-1" href="http://127.0.0.1:5000">Go to Flask App</a>
  to verify your choice.
</h4>

{% else %}
<h3 class="mb-3">You are not logged in.</h3>
<h3> Choose
  <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary mx-2">Log in</a>
  or
  <a href="{% url 'accounts:register' %}" class="btn btn-outline-secondary mx-2">Register</a>
  from navbar.
</h3>
{% endif %}

{% endblock body %}

django_app/templates/messages.html
{% if messages %}
<div class="container w-50">
  {% for message in messages %}
  {% if message.tags == 'success' %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% else %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endif %}
  
  {% endfor %}
</div>
{% endif %}